# Adjust parameter for custom analysis

# -- Temp directory for gatk -- #
TEMP_DIR: "/hpc/scratch/danilo.tatoni/temp_gatk"
slurm_log_dir: slurm-logs

# -- Base paths -- #

OUTPUT_FOLDER : "/hpc/scratch/danilo.tatoni/Neoepi_output/"

# -- Relative paths to concatenate -- #
# -- OUTPUT STRUCTURE -- #
datadirs:
  trimmed_reads: "trimmed_reads"
  trimming_report: "fastp_report"
  mapped_reads:  "mapped_reads"
  salmon_quant: "quantification"
  expression: "expression_data"
  bams: "bams"
  utils: "utils"
  HLA_typing: "HLA_typing"
  BQSR_2:  "BQSR_2"
  VCF:  "VCF"
  VCF_germ: "VCF_germ"
  VCF_out: "VCF_out"  
  pvacseq_out: "Pvacseq_out"  
  logs:
    align: "log/align"
    annotate_variants: "log/annotate_variants"
    bam_cleaning: "log/bam_cleaning"
    bam_readcount: "log/bam_readcount"
    base_recalibration: "log/base_recalibration"
    decompose: "log/decompose"
    t1k: "log/t1k"
    arcasHLA: "log/arcasHLA"
    star_idx:  "log/star_idx"
    pvacseq: "log/pvacseq"
    salmon_quant: "log/salmon_quant"
    trimming: "log/trimming"
    ref_transcript_mismatch_reporter: "log/ref_transcript_mismatch_reporter"
    snv_calling: "log/snv_calling"
    sort_bam: "log/sort_bam"
    vatools: "log/vatools"
    vcf_expression_annotator: "log/vcf_expression_annotator"
    vcf_readcount_annotator_indel: "log/vcf_readcount_annotator_indel"
    vcf_readcount_annotator_snp: "log/vcf_readcount_annotator_snp"

# -- RESOURCES -- #
# Despite the possibility to put all of them inside a single folder, the choice to write them down 
# explicitely is intentional. That's because a bioinformatic research group could already have many 
# of these files on their server in different locations, so it's useless to move them in a single 
# folder breaking existing practices e/o workflows.

resources:
  genome: "/hpc/scratch/danilo.tatoni/Exomes/VCF_resources/Homo_sapiens.GRCh38.dna.primary_assembly.fa"
  transcriptome: "/hpc/scratch/danilo.tatoni/genomes_and_indexes/Homo_sapiens.GRCh38.cdna.all.fa"
  gtf: "/hpc/scratch/danilo.tatoni/Exomes/VCF_resources/Homo_sapiens.GRCh38.105.gtf"
  star_index: "/hpc/scratch/danilo.tatoni/genomes_and_indexes/genome_index"
  salmon_idx: "/hpc/scratch/danilo.tatoni/genomes_and_indexes/salmon_index_GRCh38_ensembl"
  gsnps: "/hpc/scratch/danilo.tatoni/Exomes/VCF_resources/1000G_phase1.snps.high_confidence.hg38.vcf.gz"
  dbsnps: "/hpc/scratch/danilo.tatoni/Exomes/VCF_resources/dbsnp_146.hg38.vcf.gz"
  indel: "/hpc/scratch/danilo.tatoni/Exomes/VCF_resources/Homo_sapiens_assembly38.known_indels.vcf.gz"
  mutect_reference: "/hpc/scratch/danilo.tatoni/Exomes/VCF_resources/af-only-gnomad.hg38.vcf.gz"
  PoN: "/hpc/scratch/danilo.tatoni/Exomes/VCF_resources/1000g_pon.hg38.vcf.gz"
  iedb_dir: "/hpc/scratch/danilo.tatoni/Exomes/VCF_resources/"
  vep_cache_dir: "/hpc/scratch/danilo.tatoni/Exomes/VCF_resources/vep_cache"
  vep_plugin_dir: "/hpc/scratch/danilo.tatoni/Exomes/VCF_resources/vep_plugin"
  contamination_resource: "/hpc/scratch/danilo.tatoni/Exomes/VCF_resources/small_exac_common_3.hg38.vcf.gz"
  intervals_coding: "/hpc/scratch/danilo.tatoni/Neoepitopes_Snakemake_workflow/supplementary_res/intervals_coding_clean.BED.gz"
  gatk3_jar_path: "/hpc/scratch/danilo.tatoni/Neoepitopes_Snakemake_workflow/supplementary_res/jars/GenomeAnalysisTK.jar"
  picard_path: "/hpc/scratch/danilo.tatoni/Neoepitopes_Snakemake_workflow/supplementary_res/jars/picard.jar"
# -- TOOLS PARAMS -- #
# moved from a tool centered to a resource type one 
params:
  threads:
    STAR: 16
    t1k: 8
    salmon: 8
    arcasHLA: 2
    mark_duplicates: 4
    BQSR: 4
  RAM:
    gatk: 10
    mark_duplicates: 30000
    splitNcigar: 30000
    BQSR: 30000 
  star: "--twopassMode Basic --outSAMtype BAM SortedByCoordinate --readFilesCommand zcat " # extra params for STAR
  salmon:
    index: "--keep-duplicates"
    libtype: "A"
    zip_ext: "gz"
    extra: "--gcBias --seqBias --reduceGCMemory"
  RGPU: unit1
  RGSM: 20
  mutect2: "--max-mnp-distance 0 --min-base-quality-score 20 --dont-use-soft-clipped-bases"
  strelka2:
    threads: 10
  HaplotypeCaller: 
    threshold: 20
  FilterMutectCalls: "--max-events-in-region 4 --unique-alt-read-count 4 --min-allele-fraction 0.001"
  VariantFiltration:
    window: 35
    cluster: 3
    FS: '"FS > 30.0"'
    QD: '"QD < 2.0"'
  annotate_variants:
    assembly: "GRCh38"
    filtering: "--gencode_basic --coding_only --no_intergenic"
  vcf_readcount_annotator:
    dna_or_rna: "RNA"
  vcf_expression_annotator:
    gene_or_transcript: "gene"
    colname_gene_or_transc: "Gene"
    colname_expression: "expr"
  ref_transcript_mismatch_reporter: hard
  read_depth_filter: 30
  pvacseq:
    b: ""
    perc_threshold: ""
    m: ""
    r: ""
    k: ""
    t: 1
    net_chop_threshold: ""
    a: ""
    s: ""
    normal_sample_name: ""
    p: ""
    c: ""
    normal_cov: ""
    tdna_cov: ""
    trna_cov: ""
    normal_vaf: ""
    tdna_vaf: ""
    trna_vaf: ""
    expn_val: ""
    max_transcript_support_level: ""
    #hla_alleles: "HLA-A*11:303"
    e1: "8,9,10,11"
    mhc_tools: "MHCnuggetsI NNalign NetMHC NetMHCpan PickPocket SMM SMMPMBEC SMMalign"
    #mhc_tools: "MHCflurry MHCnuggetsI NNalign NetMHC PickPocket SMM SMMPMBEC SMMalign"
