# Adjust parameter for custom analysis

# -- Temp directory for gatk -- #
TEMP_DIR: "/hpc/scratch/danilo.tatoni/temp_gatk"
slurm_log_dir: slurm-logs

# -- OUTPUT STRUCTURE -- #
datadirs:
  trimmed_reads: "/hpc/scratch/danilo.tatoni/Neoepi_output/trimmed_reads"
  trimming_report: "/hpc/scratch/danilo.tatoni/Neoepi_output/fastp_report"
  mapped_reads:  "/hpc/scratch/danilo.tatoni/Neoepi_output/mapped_reads"
  salmon_quant: "/hpc/scratch/danilo.tatoni/Neoepi_output/quantification"
  expression: "/hpc/scratch/danilo.tatoni/Neoepi_output/expression_data"
  bams: "/hpc/scratch/danilo.tatoni/Neoepi_output/bams"
  utils: "/hpc/scratch/danilo.tatoni/Neoepi_output/utils"
  HLA_typing: "/hpc/scratch/danilo.tatoni/Neoepi_output/HLA_typing"
  BQSR_2:  "/hpc/scratch/danilo.tatoni/Neoepi_output/BQSR_2"
  VCF:  "/hpc/scratch/danilo.tatoni/Neoepi_output/VCF"
  VCF_germ: "/hpc/scratch/danilo.tatoni/Neoepi_output/VCF_germ"
  VCF_out: "/hpc/scratch/danilo.tatoni/Neoepi_output/VCF_out"  
  pvacseq_out: "/hpc/scratch/danilo.tatoni/Neoepi_output/Pvacseq_out"  
  logs:
    align: "/hpc/scratch/danilo.tatoni/Neoepi_output/log/align"
    annotate_variants: "/hpc/scratch/danilo.tatoni/Neoepi_output/log/annotate_variants"
    bam_cleaning: "/hpc/scratch/danilo.tatoni/Neoepi_output/log/bam_cleaning"
    bam_readcount: "/hpc/scratch/danilo.tatoni/Neoepi_output/log/bam_readcount"
    base_recalibration: "/hpc/scratch/danilo.tatoni/Neoepi_output/log/base_recalibration"
    decompose: "/hpc/scratch/danilo.tatoni/Neoepi_output/log/decompose"
    arcasHLA: "/hpc/scratch/danilo.tatoni/Neoepi_output/log/arcasHLA"
    star_idx:  "/hpc/scratch/danilo.tatoni/Neoepi_output/log/star_idx"
    pvacseq: "/hpc/scratch/danilo.tatoni/Neoepi_output/log/pvacseq"
    salmon_quant: "/hpc/scratch/danilo.tatoni/Neoepi_output/log/salmon_quant"
    trimming: "/hpc/scratch/danilo.tatoni/Neoepi_output/log/trimming"
    ref_transcript_mismatch_reporter: "/hpc/scratch/danilo.tatoni/Neoepi_output/log/ref_transcript_mismatch_reporter"
    snv_calling: "/hpc/scratch/danilo.tatoni/Neoepi_output/log/snv_calling"
    sort_bam: "/hpc/scratch/danilo.tatoni/Neoepi_output/log/sort_bam"
    vatools: "/hpc/scratch/danilo.tatoni/Neoepi_output/log/vatools"
    vcf_expression_annotator: "/hpc/scratch/danilo.tatoni/Neoepi_output/log/vcf_expression_annotator"
    vcf_readcount_annotator_indel: "/hpc/scratch/danilo.tatoni/Neoepi_output/log/vcf_readcount_annotator_indel"
    vcf_readcount_annotator_snp: "/hpc/scratch/danilo.tatoni/Neoepi_output/log/vcf_readcount_annotator_snp"

# -- RESOURCES -- #
resources:
  genome: "/hpc/scratch/danilo.tatoni/Exomes/VCF_resources/Homo_sapiens.GRCh38.dna.primary_assembly.fa"
  transcriptome: "/hpc/scratch/danilo.tatoni/genomes_and_indexes/Homo_sapiens.GRCh38.cdna.all.fa"
  gtf: "/hpc/scratch/danilo.tatoni/Exomes/VCF_resources/Homo_sapiens.GRCh38.105.gtf"
  star_index: "/hpc/scratch/danilo.tatoni/genomes_and_indexes/genome_index"
  salmon_idx: "/hpc/scratch/danilo.tatoni/genomes_and_indexes/salmon_index_GRCh38_ensembl"
  gsnps: "/hpc/scratch/danilo.tatoni/Exomes/VCF_resources/1000G_phase1.snps.high_confidence.hg38.vcf.gz"
  dbsnps: "/hpc/scratch/danilo.tatoni/Exomes/VCF_resources/dbsnp_146.hg38.vcf.gz"
  indel: "/hpc/scratch/danilo.tatoni/Exomes/VCF_resources/Homo_sapiens_assembly38.known_indels.vcf.gz"
  mutect_reference: "/hpc/scratch/danilo.tatoni/Exomes/VCF_resources/af-only-gnomad.hg38.vcf.gz"
  PoN: "/hpc/scratch/danilo.tatoni/Exomes/VCF_resources/1000g_pon.hg38.vcf.gz"
  iedb_dir: "/hpc/scratch/danilo.tatoni/Exomes/VCF_resources/"
  vep_cache_dir: "/hpc/scratch/danilo.tatoni/Exomes/VCF_resources/vep_cache"
  vep_plugin_dir: "/hpc/scratch/danilo.tatoni/Exomes/VCF_resources/vep_plugin"
  contamination_resource: "/hpc/scratch/danilo.tatoni/Exomes/VCF_resources/small_exac_common_3.hg38.vcf.gz"
  intervals_coding: "/hpc/scratch/danilo.tatoni/Neoepitopes_Snakemake_workflow/supplementary_res/intervals_coding_clean.BED.gz"
  gatk3_jar_path: "/hpc/scratch/danilo.tatoni/Neoepitopes_Snakemake_workflow/supplementary_res/jars/GenomeAnalysisTK.jar"
  picard_path: "/hpc/scratch/danilo.tatoni/Neoepitopes_Snakemake_workflow/supplementary_res/jars/picard.jar"
# -- TOOLS PARAMS -- #
# moved from a tool centered to a resource type one 
params:
  threads:
    STAR: 16
    salmon: 8
    arcasHLA: 2
    mark_duplicates: 4
    BQSR: 4
  RAM:
    gatk: 10
    mark_duplicates: 30000
    splitNcigar: 30000
    BQSR: 30000 
  star: "--twopassMode Basic --outSAMtype BAM Unsorted --readFilesCommand zcat " # extra params for STAR
  salmon:
    libtype: "A"
    zip_ext: "gz"
    extra: "--gcBias --seqBias --reduceGCMemory"
  RGPU: unit1
  RGSM: 20
  mutect2: "--max-mnp-distance 0 --min-base-quality-score 20 --dont-use-soft-clipped-bases"
  strelka2:
    threads: 10
  HaplotypeCaller: 
    threshold: 20
  FilterMutectCalls: "--max-events-in-region 4 --unique-alt-read-count 4 --min-allele-fraction 0.001"
  VariantFiltration:
    window: 35
    cluster: 3
    FS: '"FS > 30.0"'
    QD: '"QD < 2.0"'
  annotate_variants:
    assembly: "GRCh38"
  vcf_readcount_annotator:
    dna_or_rna: "RNA"
  vcf_expression_annotator:
    gene_or_transcript: "gene"
    colname_gene_or_transc: "Gene"
    colname_expression: "expr"
  ref_transcript_mismatch_reporter: hard
  read_depth_filter: 30
  pvacseq:
    b: ""
    perc_threshold: ""
    m: ""
    r: ""
    k: ""
    t: 1
    net_chop_threshold: ""
    a: ""
    s: ""
    normal_sample_name: ""
    p: ""
    c: ""
    normal_cov: ""
    tdna_cov: ""
    trna_cov: ""
    normal_vaf: ""
    tdna_vaf: ""
    trna_vaf: ""
    expn_val: ""
    max_transcript_support_level: ""
    #hla_alleles: "HLA-A*11:303"
    e1: "8,9,10,11"
    mhc_tools: "MHCnuggetsI NNalign NetMHC NetMHCpan PickPocket SMM SMMPMBEC SMMalign"
    #mhc_tools: "MHCflurry MHCnuggetsI NNalign NetMHC PickPocket SMM SMMPMBEC SMMalign"
