[[annotation]]
file=""
fields=["AN","AC","AF"]
names=["gnomAD_AN","gnomAD_AC", "gnomAD_AF"]
ops=["self", "self", "self"]

[[annotation]]
file=""
fields=["ID", "AN","AC","AF"]
names=["dbsnpID","alfa_AN","alfa_AC", "alfa_AF"]
ops=["self","self", "self", "self"]

[[annotation]]
file=""
columns=[7]
names=['REDI_db']
ops=['self']    

[[annotation]]
file=""
fields=["AF"]
names=["exAC_AF"]
ops=["self"]

[[annotation]]
file=""
fields=["AN","AC","AF"]
names=["indels_AN", "indels_AC", "indels_AF"]
ops=["self", "self", "self"]

[[annotation]]
file=""
fields=["ID","CNT"]
names=["cosmicID", "cosmic_cnt"]
ops=["self", "self"]

[[postannotation]]
name="ID"
fields=["dbsnpID","cosmicID","ID"]
type="String"
op="concat"

[[postannotation]]
fields=["dbsnpID","cosmicID"]
op="delete"