name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format code
        uses: psf/black@stable
        with:
          options: ". --verbose"
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --quiet && git diff --staged --quiet || (git add . ; git commit -m "Black formatting")
      
#  Linting:
#    needs: Formatting
#   runs-on: ubuntu-latest
#   steps:
#     - uses: actions/checkout@v2
#      - name: Test linting
#        uses: snakemake/snakemake-github-action@v1.23.0
#       with:
#         directory: .
#         snakefile: workflow/Snakefile
#         args: "--lint"
  Testing:
    runs-on: ubuntu-latest
    needs: 
      - Formatting
    steps:
    - uses: actions/checkout@v2
    - name: Test workflow
      uses: snakemake/snakemake-github-action@v1.23.0
      with:
        snakefile: workflow/Snakefile
        args: "--use-conda --use-singularity --show-failed-logs -j 10 --conda-cleanup-pkgs cache --conda-frontend conda"
        stagein: "conda config --set channel_priority flexible"
