name: Testing

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test workflow
      uses: snakemake/snakemake-github-action@v1.23.0
      with:
        snakefile: workflow/Snakefile
        args: "--use-conda --software-deployment-method apptainer --show-failed-logs -j 10 --conda-cleanup-pkgs cache --conda-frontend conda "
        directory: .
        stagein: "conda config --set channel_priority flexible"
