name: Testing

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda install -c conda-forge mamba
    - name: Setup snakemake
      run: |
        mamba install -c conda-forge -c bioconda snakemake singularity sra-tools
    - name: Download example data
      run: |
        fastq-dump fastq-dump SRR9697665 --gzip --split-files -O test_data
        echo "NCI_4283,test_data/SRR9697665_1.fastq.gz,test_data/SRR9697665_2.fastq.gz" >> units.csv
        echo "NCI_4283" >> patients.csv
        
    - run: echo "Finish installing snakemake"
    - name: Run snakemake
      run: |
        snakemake --use-singularity --use-conda --cores 4
